from _typeshed import Incomplete
from pydrake.common.value import Value as Value
from pydrake.geometry import Box as Box, Convex as Convex, Cylinder as Cylinder, HalfSpace as HalfSpace, Mesh as Mesh, QueryObject as QueryObject, ReadObjToTriangleSurfaceMesh as ReadObjToTriangleSurfaceMesh, Rgba as Rgba, Role as Role, Sphere as Sphere, optimization as optimization
from pydrake.math import RigidTransform as RigidTransform
from pydrake.systems.pyplot_visualizer import PyPlotVisualizer as PyPlotVisualizer

class PlanarSceneGraphVisualizer(PyPlotVisualizer):
    def __init__(self, scene_graph, draw_period: Incomplete | None = ..., T_VW=..., xlim=..., ylim=..., facecolor=..., use_random_colors: bool = ..., substitute_collocated_mesh_files: bool = ..., ax: Incomplete | None = ..., show: Incomplete | None = ...) -> None: ...
    def get_geometry_query_input_port(self): ...
    @staticmethod
    def frame_name(frame_id, inspector): ...
    def draw(self, context) -> None: ...

def ConnectPlanarSceneGraphVisualizer(builder, scene_graph, output_port: Incomplete | None = ..., **kwargs): ...
