import yaml
from _typeshed import Incomplete
from typing import NamedTuple

class _SchemaLoader(yaml.loader.SafeLoader): ...

def yaml_load_data(data, *, private: bool = ...): ...
def yaml_load_file(filename, *, private: bool = ...): ...
def yaml_load(*, data: Incomplete | None = ..., filename: Incomplete | None = ..., private: bool = ...): ...

class _SchemaDumper(yaml.dumper.SafeDumper): ...

def yaml_dump(data, *, filename: Incomplete | None = ...): ...

class _LoadYamlOptions(NamedTuple):
    allow_yaml_with_no_schema: Incomplete
    allow_schema_with_no_yaml: Incomplete
    retain_map_defaults: Incomplete

def yaml_load_typed(*, schema, data: Incomplete | None = ..., filename: Incomplete | None = ..., child_name: Incomplete | None = ..., defaults: Incomplete | None = ..., allow_yaml_with_no_schema: bool = ..., allow_schema_with_no_yaml: bool = ..., retain_map_defaults: bool = ...): ...
