//@ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Runtime Common Library
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * This is a Generic status enumeration that will be used for the status of dns and pod or cloud.
 * @export
 * @enum {string}
 */
export enum AllocationStatusEnum {
    Pending = 'PENDING',
    Running = 'RUNNING',
    Failed = 'FAILED',
    Succeeded = 'SUCCEEDED',
    Unknown = 'UNKNOWN'
}

export function AllocationStatusEnumFromJSON(json: any): AllocationStatusEnum {
    return AllocationStatusEnumFromJSONTyped(json, false);
}

export function AllocationStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllocationStatusEnum {
    return json as AllocationStatusEnum;
}

export function AllocationStatusEnumToJSON(value?: AllocationStatusEnum | null): any {
    return value as any;
}

