//@ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Runtime Common Library
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AllocationStatusEnum,
    AllocationStatusEnumFromJSON,
    AllocationStatusEnumFromJSONTyped,
    AllocationStatusEnumToJSON,
    EmbeddedModelSchema,
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './';

/**
 * 
 * @export
 * @interface AllocationCloudStatus
 */
export interface AllocationCloudStatus {
    /**
     * 
     * @type {EmbeddedModelSchema}
     * @memberof AllocationCloudStatus
     */
    schema?: EmbeddedModelSchema;
    /**
     * 
     * @type {AllocationStatusEnum}
     * @memberof AllocationCloudStatus
     */
    cloud: AllocationStatusEnum;
}

export function AllocationCloudStatusFromJSON(json: any): AllocationCloudStatus {
    return AllocationCloudStatusFromJSONTyped(json, false);
}

export function AllocationCloudStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllocationCloudStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'cloud': AllocationStatusEnumFromJSON(json['cloud']),
    };
}

export function AllocationCloudStatusToJSON(value?: AllocationCloudStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'cloud': AllocationStatusEnumToJSON(value.cloud),
    };
}


