//@ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Runtime Common Library
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * These are all of the available event types that are permitted in an object pair notation.
 * @export
 * @interface AnalyticsTrackedAssetEventIdentifierDescriptionPairs
 */
export interface AnalyticsTrackedAssetEventIdentifierDescriptionPairs {
    /**
     * The key value pair for an asset being created.
     * @type {string}
     * @memberof AnalyticsTrackedAssetEventIdentifierDescriptionPairs
     */
    assetCreated?: AnalyticsTrackedAssetEventIdentifierDescriptionPairsAssetCreatedEnum;
    /**
     * An asset was viewed
     * @type {string}
     * @memberof AnalyticsTrackedAssetEventIdentifierDescriptionPairs
     */
    assetViewed?: AnalyticsTrackedAssetEventIdentifierDescriptionPairsAssetViewedEnum;
    /**
     * An asset's format was copied
     * @type {string}
     * @memberof AnalyticsTrackedAssetEventIdentifierDescriptionPairs
     */
    assetFormatCopied?: AnalyticsTrackedAssetEventIdentifierDescriptionPairsAssetFormatCopiedEnum;
    /**
     * An asset's format was downloaded
     * @type {string}
     * @memberof AnalyticsTrackedAssetEventIdentifierDescriptionPairs
     */
    assetFormatDownloaded?: AnalyticsTrackedAssetEventIdentifierDescriptionPairsAssetFormatDownloadedEnum;
    /**
     * An asset was deleted or not
     * @type {string}
     * @memberof AnalyticsTrackedAssetEventIdentifierDescriptionPairs
     */
    assetDeleted?: AnalyticsTrackedAssetEventIdentifierDescriptionPairsAssetDeletedEnum;
    /**
     * An asset was redescribed by the user
     * @type {string}
     * @memberof AnalyticsTrackedAssetEventIdentifierDescriptionPairs
     */
    assetDescriptionUpdated?: AnalyticsTrackedAssetEventIdentifierDescriptionPairsAssetDescriptionUpdatedEnum;
    /**
     * An asset was renamed by the user
     * @type {string}
     * @memberof AnalyticsTrackedAssetEventIdentifierDescriptionPairs
     */
    assetNameUpdated?: AnalyticsTrackedAssetEventIdentifierDescriptionPairsAssetNameUpdatedEnum;
    /**
     * A generic classification was changed on a format within an asset
     * @type {string}
     * @memberof AnalyticsTrackedAssetEventIdentifierDescriptionPairs
     */
    assetFormatGenericClassificationUpdated?: AnalyticsTrackedAssetEventIdentifierDescriptionPairsAssetFormatGenericClassificationUpdatedEnum;
    /**
     * A specific classification was changed on a format within an asset
     * @type {string}
     * @memberof AnalyticsTrackedAssetEventIdentifierDescriptionPairs
     */
    assetFormatSpecificClassificationUpdated?: AnalyticsTrackedAssetEventIdentifierDescriptionPairsAssetFormatSpecificClassificationUpdatedEnum;
    /**
     * 
     * @type {string}
     * @memberof AnalyticsTrackedAssetEventIdentifierDescriptionPairs
     */
    assetCreationFailed?: AnalyticsTrackedAssetEventIdentifierDescriptionPairsAssetCreationFailedEnum;
    /**
     * 
     * @type {string}
     * @memberof AnalyticsTrackedAssetEventIdentifierDescriptionPairs
     */
    assetTagAdded?: AnalyticsTrackedAssetEventIdentifierDescriptionPairsAssetTagAddedEnum;
    /**
     * 
     * @type {string}
     * @memberof AnalyticsTrackedAssetEventIdentifierDescriptionPairs
     */
    assetLinkAdded?: AnalyticsTrackedAssetEventIdentifierDescriptionPairsAssetLinkAddedEnum;
    /**
     * user generated a link for asset
     * @type {string}
     * @memberof AnalyticsTrackedAssetEventIdentifierDescriptionPairs
     */
    assetLinkGenerated?: AnalyticsTrackedAssetEventIdentifierDescriptionPairsAssetLinkGeneratedEnum;
    /**
     * 
     * @type {string}
     * @memberof AnalyticsTrackedAssetEventIdentifierDescriptionPairs
     */
    assetLinkDeleted?: AnalyticsTrackedAssetEventIdentifierDescriptionPairsAssetLinkDeletedEnum;
    /**
     * 
     * @type {string}
     * @memberof AnalyticsTrackedAssetEventIdentifierDescriptionPairs
     */
    assetTagDeleted?: AnalyticsTrackedAssetEventIdentifierDescriptionPairsAssetTagDeletedEnum;
}

/**
* @export
* @enum {string}
*/
export enum AnalyticsTrackedAssetEventIdentifierDescriptionPairsAssetCreatedEnum {
    AnAssetWasCreated = 'an_asset_was_created'
}/**
* @export
* @enum {string}
*/
export enum AnalyticsTrackedAssetEventIdentifierDescriptionPairsAssetViewedEnum {
    AnAssetWasViewed = 'an_asset_was_viewed'
}/**
* @export
* @enum {string}
*/
export enum AnalyticsTrackedAssetEventIdentifierDescriptionPairsAssetFormatCopiedEnum {
    AnAssetPreviewFormatWasCopied = 'an_asset_preview_format_was_copied'
}/**
* @export
* @enum {string}
*/
export enum AnalyticsTrackedAssetEventIdentifierDescriptionPairsAssetFormatDownloadedEnum {
    AnAssetFormatWasDownloaded = 'an_asset_format_was_downloaded'
}/**
* @export
* @enum {string}
*/
export enum AnalyticsTrackedAssetEventIdentifierDescriptionPairsAssetDeletedEnum {
    AnAssetWasDeleted = 'an_asset_was_deleted'
}/**
* @export
* @enum {string}
*/
export enum AnalyticsTrackedAssetEventIdentifierDescriptionPairsAssetDescriptionUpdatedEnum {
    AnAssetWasRedescribedByTheUser = 'an_asset_was_redescribed_by_the_user'
}/**
* @export
* @enum {string}
*/
export enum AnalyticsTrackedAssetEventIdentifierDescriptionPairsAssetNameUpdatedEnum {
    AnAssetWasRenamedByTheUser = 'an_asset_was_renamed_by_the_user'
}/**
* @export
* @enum {string}
*/
export enum AnalyticsTrackedAssetEventIdentifierDescriptionPairsAssetFormatGenericClassificationUpdatedEnum {
    AGenericClassificationWasChangedOnAFormatWithinAnAsset = 'a_generic_classification_was_changed_on_a_format_within_an_asset'
}/**
* @export
* @enum {string}
*/
export enum AnalyticsTrackedAssetEventIdentifierDescriptionPairsAssetFormatSpecificClassificationUpdatedEnum {
    ASpecificClassificationWasChangedOnAFormatWithinAnAsset = 'a_specific_classification_was_changed_on_a_format_within_an_asset'
}/**
* @export
* @enum {string}
*/
export enum AnalyticsTrackedAssetEventIdentifierDescriptionPairsAssetCreationFailedEnum {
    AnAssetFailedToBeCreated = 'an_asset_failed_to_be_created'
}/**
* @export
* @enum {string}
*/
export enum AnalyticsTrackedAssetEventIdentifierDescriptionPairsAssetTagAddedEnum {
    ATagWasAddedByTheUser = 'a_tag_was_added_by_the_user'
}/**
* @export
* @enum {string}
*/
export enum AnalyticsTrackedAssetEventIdentifierDescriptionPairsAssetLinkAddedEnum {
    ALinkWasAddedByTheUser = 'a_link_was_added_by_the_user'
}/**
* @export
* @enum {string}
*/
export enum AnalyticsTrackedAssetEventIdentifierDescriptionPairsAssetLinkGeneratedEnum {
    AnAssetLinkWasGenerated = 'an_asset_link_was_generated'
}/**
* @export
* @enum {string}
*/
export enum AnalyticsTrackedAssetEventIdentifierDescriptionPairsAssetLinkDeletedEnum {
    ALinkWasDeletedByTheUser = 'a_link_was_deleted_by_the_user'
}/**
* @export
* @enum {string}
*/
export enum AnalyticsTrackedAssetEventIdentifierDescriptionPairsAssetTagDeletedEnum {
    ATagWasDeletedByTheUser = 'a_tag_was_deleted_by_the_user'
}

export function AnalyticsTrackedAssetEventIdentifierDescriptionPairsFromJSON(json: any): AnalyticsTrackedAssetEventIdentifierDescriptionPairs {
    return AnalyticsTrackedAssetEventIdentifierDescriptionPairsFromJSONTyped(json, false);
}

export function AnalyticsTrackedAssetEventIdentifierDescriptionPairsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsTrackedAssetEventIdentifierDescriptionPairs {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'assetCreated': !exists(json, 'asset_created') ? undefined : json['asset_created'],
        'assetViewed': !exists(json, 'asset_viewed') ? undefined : json['asset_viewed'],
        'assetFormatCopied': !exists(json, 'asset_format_copied') ? undefined : json['asset_format_copied'],
        'assetFormatDownloaded': !exists(json, 'asset_format_downloaded') ? undefined : json['asset_format_downloaded'],
        'assetDeleted': !exists(json, 'asset_deleted') ? undefined : json['asset_deleted'],
        'assetDescriptionUpdated': !exists(json, 'asset_description_updated') ? undefined : json['asset_description_updated'],
        'assetNameUpdated': !exists(json, 'asset_name_updated') ? undefined : json['asset_name_updated'],
        'assetFormatGenericClassificationUpdated': !exists(json, 'asset_format_generic_classification_updated') ? undefined : json['asset_format_generic_classification_updated'],
        'assetFormatSpecificClassificationUpdated': !exists(json, 'asset_format_specific_classification_updated') ? undefined : json['asset_format_specific_classification_updated'],
        'assetCreationFailed': !exists(json, 'asset_creation_failed') ? undefined : json['asset_creation_failed'],
        'assetTagAdded': !exists(json, 'asset_tag_added') ? undefined : json['asset_tag_added'],
        'assetLinkAdded': !exists(json, 'asset_link_added') ? undefined : json['asset_link_added'],
        'assetLinkGenerated': !exists(json, 'asset_link_generated') ? undefined : json['asset_link_generated'],
        'assetLinkDeleted': !exists(json, 'asset_link_deleted') ? undefined : json['asset_link_deleted'],
        'assetTagDeleted': !exists(json, 'asset_tag_deleted') ? undefined : json['asset_tag_deleted'],
    };
}

export function AnalyticsTrackedAssetEventIdentifierDescriptionPairsToJSON(value?: AnalyticsTrackedAssetEventIdentifierDescriptionPairs | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'asset_created': value.assetCreated,
        'asset_viewed': value.assetViewed,
        'asset_format_copied': value.assetFormatCopied,
        'asset_format_downloaded': value.assetFormatDownloaded,
        'asset_deleted': value.assetDeleted,
        'asset_description_updated': value.assetDescriptionUpdated,
        'asset_name_updated': value.assetNameUpdated,
        'asset_format_generic_classification_updated': value.assetFormatGenericClassificationUpdated,
        'asset_format_specific_classification_updated': value.assetFormatSpecificClassificationUpdated,
        'asset_creation_failed': value.assetCreationFailed,
        'asset_tag_added': value.assetTagAdded,
        'asset_link_added': value.assetLinkAdded,
        'asset_link_generated': value.assetLinkGenerated,
        'asset_link_deleted': value.assetLinkDeleted,
        'asset_tag_deleted': value.assetTagDeleted,
    };
}


