//@ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Runtime Common Library
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalyticsTrackedSegmentEventContextApp
 */
export interface AnalyticsTrackedSegmentEventContextApp {
    /**
     * The name of the current app
     * @type {string}
     * @memberof AnalyticsTrackedSegmentEventContextApp
     */
    name: string;
    /**
     * The version of the application
     * @type {string}
     * @memberof AnalyticsTrackedSegmentEventContextApp
     */
    version: string;
}

export function AnalyticsTrackedSegmentEventContextAppFromJSON(json: any): AnalyticsTrackedSegmentEventContextApp {
    return AnalyticsTrackedSegmentEventContextAppFromJSONTyped(json, false);
}

export function AnalyticsTrackedSegmentEventContextAppFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsTrackedSegmentEventContextApp {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'version': json['version'],
    };
}

export function AnalyticsTrackedSegmentEventContextAppToJSON(value?: AnalyticsTrackedSegmentEventContextApp | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'version': value.version,
    };
}


