//@ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Runtime Common Library
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApigeeApp,
    ApigeeAppFromJSON,
    ApigeeAppFromJSONTyped,
    ApigeeAppToJSON,
} from './';

/**
 * 
 * @export
 * @interface ApigeeListAppsResponse
 */
export interface ApigeeListAppsResponse {
    /**
     * 
     * @type {Array<ApigeeApp>}
     * @memberof ApigeeListAppsResponse
     */
    app?: Array<ApigeeApp>;
}

export function ApigeeListAppsResponseFromJSON(json: any): ApigeeListAppsResponse {
    return ApigeeListAppsResponseFromJSONTyped(json, false);
}

export function ApigeeListAppsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApigeeListAppsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'app': !exists(json, 'app') ? undefined : ((json['app'] as Array<any>).map(ApigeeAppFromJSON)),
    };
}

export function ApigeeListAppsResponseToJSON(value?: ApigeeListAppsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'app': value.app === undefined ? undefined : ((value.app as Array<any>).map(ApigeeAppToJSON)),
    };
}


