//@ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Runtime Common Library
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum Mime {
    TextCss = 'text/css',
    TextXDart = 'text/x-dart',
    TextHtml = 'text/html',
    TextXJavaSource = 'text/x-java-source',
    ApplicationJavascript = 'application/javascript',
    ApplicationJson = 'application/json',
    ApplicationPostscript = 'application/postscript',
    ApplicationWasm = 'application/wasm',
    ApplicationRtf = 'application/rtf',
    ApplicationXCocoa = 'application/x-cocoa',
    ApplicationXPerl = 'application/x-perl',
    ApplicationXhtmlXml = 'application/xhtml-xml',
    TextXml = 'text/xml',
    TextPlain = 'text/plain',
    ApplicationEcmascript = 'application/ecmascript',
    ApplicationNode = 'application/node',
    ApplicationXHttpdPhp = 'application/x-httpd-php',
    TextXScriptPython = 'text/x-script.python',
    ApplicationXBytecodePython = 'application/x-bytecode.python',
    ApplicationJava = 'application/java',
    TextCX = 'text/c-x',
    TextXC = 'text/x-c',
    TextXPascal = 'text/x-pascal',
    TextCndCurl = 'text/cnd.curl',
    TextVndCurlMcurl = 'text/vnd.curl.mcurl',
    TextCsv = 'text/csv',
    ApplicationMsword = 'application/msword',
    ApplicationVndMsWordDocumentMacroenabled12 = 'application/vnd.ms-word.document.macroenabled.12',
    ApplicationVndOpenxmlformatsOfficedocumentWordprocessingmlDocument = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    ApplicationXMsdownload = 'application/x-msdownload',
    ImageGif = 'image/gif',
    ImageXIcon = 'image/x-icon',
    ImageJpeg = 'image/jpeg',
    VideoJpm = 'video/jpm',
    AudioMpeg = 'audio/mpeg',
    VideoMp4 = 'video/mp4',
    AudioMp4 = 'audio/mp4',
    AudioOgg = 'audio/ogg',
    VideoOgg = 'video/ogg',
    ApplicationOgg = 'application/ogg',
    ApplicationVndMsPowerpoint = 'application/vnd.ms-powerpoint',
    ApplicationVndOpenxmlformatsOfficedocumentPresentationmlPresentation = 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    ApplicationVndMsPowerpointPresentationMacroenabled12 = 'application/vnd.ms-powerpoint.presentation.macroenabled.12',
    VideoQuicktime = 'video/quicktime',
    ImageTiff = 'image/tiff',
    AudioXWav = 'audio/x-wav',
    AudioWebm = 'audio/webm',
    VideoWebm = 'video/webm',
    ImageWebp = 'image/webp',
    ApplicationVndMsExcel = 'application/vnd.ms-excel',
    ApplicationVndMsExcelAddinMacroenabled12 = 'application/vnd.ms-excel.addin.macroenabled.12',
    ApplicationVndMsExcelSheetBinaryMacroenabled12 = 'application/vnd.ms-excel.sheet.binary.macroenabled.12',
    ApplicationVndMsExcelSheetMacroenabled12 = 'application/vnd.ms-excel.sheet.macroenabled.12',
    ApplicationVndOpenxmlformatsOfficedocumentSpreadsheetmlSheet = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    ApplicationVndMsExcelTemplateMacroenabled12 = 'application/vnd.ms-excel.template.macroenabled.12',
    ApplicationVndOpenxmlformatsOfficedocumentSpreadsheetmlTemplate = 'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
    ApplicationPdf = 'application/pdf',
    ImagePng = 'image/png',
    ApplicationXRedhatPackageManager = 'application/x-redhat-package-manager',
    ApplicationZip = 'application/zip',
    FontWoff = 'font/woff',
    FontWoff2 = 'font/woff2',
    ApplicationOctetStream = 'application/octet-stream',
    ApplicationMacBinary = 'application/mac-binary',
    ApplicationXBinary = 'application/x-binary',
    ApplicationXMacbinary = 'application/x-macbinary',
    ImageBmp = 'image/bmp',
    ApplicationVndMsFontobject = 'application/vnd.ms-fontobject',
    ApplicationGzip = 'application/gzip',
    ApplicationJavaArchive = 'application/java-archive',
    ApplicationVndAppleInstallerXml = 'application/vnd.apple.installer_xml',
    TextXScriptZsh = 'text/x-script.zsh',
    ApplicationXAppleDiskimage = 'application/x-apple-diskimage',
    TextRichtext = 'text/richtext',
    TextUriList = 'text/uri-list',
    ApplicationJsonmlJson = 'application/jsonml_json',
    ApplicationSsmlXml = 'application/ssml_xml',
    ApplicationXamlXml = 'application/xaml_xml',
    ApplicationRssXml = 'application/rss_xml'
}

export function MimeFromJSON(json: any): Mime {
    return MimeFromJSONTyped(json, false);
}

export function MimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Mime {
    return json as Mime;
}

export function MimeToJSON(value?: Mime | null): any {
    return value as any;
}

