//@ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Runtime Common Library
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EmbeddedModelSchema,
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
    ModelDownloadProgressStatusEnum,
    ModelDownloadProgressStatusEnumFromJSON,
    ModelDownloadProgressStatusEnumFromJSONTyped,
    ModelDownloadProgressStatusEnumToJSON,
} from './';

/**
 * This is the model that is sent over our ws for streaming the progress of a model that is being downloaded.
 * 
 * can eventually add a number that display the percentage downloaded an so on.
 * @export
 * @interface ModelDownloadProgress
 */
export interface ModelDownloadProgress {
    /**
     * 
     * @type {EmbeddedModelSchema}
     * @memberof ModelDownloadProgress
     */
    schema?: EmbeddedModelSchema;
    /**
     * 
     * @type {ModelDownloadProgressStatusEnum}
     * @memberof ModelDownloadProgress
     */
    status?: ModelDownloadProgressStatusEnum;
}

export function ModelDownloadProgressFromJSON(json: any): ModelDownloadProgress {
    return ModelDownloadProgressFromJSONTyped(json, false);
}

export function ModelDownloadProgressFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelDownloadProgress {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'status': !exists(json, 'status') ? undefined : ModelDownloadProgressStatusEnumFromJSON(json['status']),
    };
}

export function ModelDownloadProgressToJSON(value?: ModelDownloadProgress | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'status': ModelDownloadProgressStatusEnumToJSON(value.status),
    };
}


