//@ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Runtime Common Library
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EmbeddedModelSchema,
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
    FlattenedAssets,
    FlattenedAssetsFromJSON,
    FlattenedAssetsFromJSONTyped,
    FlattenedAssetsToJSON,
} from './';

/**
 * This is a model of all optional properties, that will get returned from /assets/pseudo.
 * @export
 * @interface PseudoAssets
 */
export interface PseudoAssets {
    /**
     * 
     * @type {EmbeddedModelSchema}
     * @memberof PseudoAssets
     */
    schema?: EmbeddedModelSchema;
    /**
     * 
     * @type {FlattenedAssets}
     * @memberof PseudoAssets
     */
    identifiers?: FlattenedAssets;
}

export function PseudoAssetsFromJSON(json: any): PseudoAssets {
    return PseudoAssetsFromJSONTyped(json, false);
}

export function PseudoAssetsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PseudoAssets {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'identifiers': !exists(json, 'identifiers') ? undefined : FlattenedAssetsFromJSON(json['identifiers']),
    };
}

export function PseudoAssetsToJSON(value?: PseudoAssets | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'identifiers': FlattenedAssetsToJSON(value.identifiers),
    };
}


