//@ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Runtime Common Library
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EmbeddedModelSchema,
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './';

/**
 * A response object from segment.
 * @export
 * @interface SegmentResponse
 */
export interface SegmentResponse {
    /**
     * 
     * @type {EmbeddedModelSchema}
     * @memberof SegmentResponse
     */
    schema?: EmbeddedModelSchema;
    /**
     * If we succeeded or not.
     * @type {boolean}
     * @memberof SegmentResponse
     */
    success: boolean;
}

export function SegmentResponseFromJSON(json: any): SegmentResponse {
    return SegmentResponseFromJSONTyped(json, false);
}

export function SegmentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SegmentResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'success': json['success'],
    };
}

export function SegmentResponseToJSON(value?: SegmentResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'success': value.success,
    };
}


