//@ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Runtime Common Library
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EmbeddedModelSchema,
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
} from './';

/**
 * 
 * @export
 * @interface TLPCodeFragmentSuggestedReuse
 */
export interface TLPCodeFragmentSuggestedReuse {
    /**
     * 
     * @type {EmbeddedModelSchema}
     * @memberof TLPCodeFragmentSuggestedReuse
     */
    schema?: EmbeddedModelSchema;
    /**
     * 
     * @type {string}
     * @memberof TLPCodeFragmentSuggestedReuse
     */
    id?: string;
}

export function TLPCodeFragmentSuggestedReuseFromJSON(json: any): TLPCodeFragmentSuggestedReuse {
    return TLPCodeFragmentSuggestedReuseFromJSONTyped(json, false);
}

export function TLPCodeFragmentSuggestedReuseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TLPCodeFragmentSuggestedReuse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function TLPCodeFragmentSuggestedReuseToJSON(value?: TLPCodeFragmentSuggestedReuse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'id': value.id,
    };
}


