//@ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Runtime Common Library
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TrackedSummaryProperties,
    TrackedSummaryPropertiesFromJSON,
    TrackedSummaryPropertiesFromJSONTyped,
    TrackedSummaryPropertiesToJSON,
} from './';

/**
 * This is the tracked model used for gathering a summary report of a users top level analytics.
 * @export
 * @interface TrackedSummary
 */
export interface TrackedSummary {
    /**
     * this is a segment property.
     * @type {string}
     * @memberof TrackedSummary
     */
    userId?: string;
    /**
     * this is the os id.
     * @type {string}
     * @memberof TrackedSummary
     */
    anonymousId: string;
    /**
     * ensure this is in utc when sending.
     * @type {string}
     * @memberof TrackedSummary
     */
    timestamp: string;
    /**
     * 
     * @type {TrackedSummaryProperties}
     * @memberof TrackedSummary
     */
    properties: TrackedSummaryProperties;
    /**
     * 
     * @type {string}
     * @memberof TrackedSummary
     */
    event: string;
}

export function TrackedSummaryFromJSON(json: any): TrackedSummary {
    return TrackedSummaryFromJSONTyped(json, false);
}

export function TrackedSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackedSummary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'anonymousId': json['anonymousId'],
        'timestamp': json['timestamp'],
        'properties': TrackedSummaryPropertiesFromJSON(json['properties']),
        'event': json['event'],
    };
}

export function TrackedSummaryToJSON(value?: TrackedSummary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'anonymousId': value.anonymousId,
        'timestamp': value.timestamp,
        'properties': TrackedSummaryPropertiesToJSON(value.properties),
        'event': value.event,
    };
}


