#ifndef NUMAARON_CORE_SRC_MULTIARRAY_GETSET_H_
#define NUMAARON_CORE_SRC_MULTIARRAY_GETSET_H_

extern NPY_NO_EXPORT PyGetSetDef array_getsetlist[];

#endif  /* NUMAARON_CORE_SRC_MULTIARRAY_GETSET_H_ */
