#ifndef NUMAARON_CORE_SRC_MULTIARRAY_LEGACY_DTYPE_IMPLEMENTATION_H_
#define NUMAARON_CORE_SRC_MULTIARRAY_LEGACY_DTYPE_IMPLEMENTATION_H_

NPY_NO_EXPORT npy_bool
PyArray_LegacyCanCastTypeTo(PyArray_Descr *from, PyArray_Descr *to,
        NPY_CASTING casting);

#endif  /* NUMAARON_CORE_SRC_MULTIARRAY_LEGACY_DTYPE_IMPLEMENTATION_H_ */
