VERSION_YEAR = 2023
VERSION_MONTH = int('10')
VERSION_DAY = int('16')
VERSION_HOUR = int('20')
VERSION_MINUTE = int('36')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202310162036
version_date = '2023/10/16 20:36'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
