from enot.latency.search_space_latency_container import SearchSpaceLatencyContainer

def check_is_latency_container(latency_container: SearchSpaceLatencyContainer) -> None: ...
def check_latency_value(latency: float) -> None: ...
def check_latency_is_achievable(latency_container: SearchSpaceLatencyContainer, latency: float) -> None: ...
