
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-13T15:42:44+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "eb8c8a597f6c77a786abb974b3c2a738c92b178d",
 "version": "5.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
