
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-12T15:54:04-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "8996e4a423474e6ae1e262b809ab3943ae5b05ad",
 "version": "2.13.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
