
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-11T10:36:06-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "8dd1727c102ad8a7469084810fdd792ae6a5dd4a",
 "version": "23.10.00"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
