THEME_COLORS = {
    'light': {
        'bg': 'bg-white',
        'text': 'text-gray-900',
        'background_light': 'bg-gray-100',
        'background_dark': 'bg-gray-300',
        'background_footer': 'bg-gray-200',
        'text-dark': 'text-gray-900',
        'ring': 'ring-gray-400',
        'hover': 'hover:bg-gray-50',
    },
    'dark': {
        'bg': 'bg-gray-800',
        'text': 'text-white',
        'background_light': 'bg-gray-900',
        'background_dark': 'bg-gray-700',
        'background_footer': 'bg-gray-600',
        'text-dark': 'text-gray-900',
        'ring': 'ring-gray-400',
        'hover': 'hover:bg-gray-700',
    },
    'pink': {
        'bg': 'bg-pink-200',
        'text': 'text-pink-900',
        'background_light': 'bg-pink-100',
        'background_dark': 'bg-pink-300',
        'background_footer': 'bg-pink-200',
        'ring': 'ring-pink-400',
        'hover': 'hover:bg-pink-400',
    },
    'blue': {
        'bg': 'bg-blue-200',
        'text': 'text-blue-900',
        'background_light': 'bg-blue-100',
        'background_dark': 'bg-blue-300',
        'background_footer': 'bg-blue-200',
        'ring': 'ring-blue-400',
        'hover': 'hover:bg-blue-400',
    },
    'green': {
        'bg': 'bg-green-200',
        'text': 'text-green-900',
        'background_light': 'bg-green-100',
        'background_dark': 'bg-green-300',
        'background_footer': 'bg-green-200',
        'ring': 'ring-green-400',
        'hover': 'hover:bg-green-400',
    },
    'yellow': {
        'bg': 'bg-yellow-200',
        'text': 'text-yellow-900',
        'background_light': 'bg-yellow-100',
        'background_dark': 'bg-yellow-300',
        'background_footer': 'bg-yellow-200',
        'ring': 'ring-yellow-400',
        'hover': 'hover:bg-yellow-400',
    },
    'red': {
        'bg': 'bg-red-200',
        'text': 'text-red-900',
        'background_light': 'bg-red-100',
        'background_dark': 'bg-red-300',
        'background_footer': 'bg-red-200',
        'ring': 'ring-red-400',
        'hover': 'hover:bg-red-400',
    },
}