//@ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * This is an open API that holds specific endpoints as a base for Pieces Context Systems
 * The point of this API is to allow us to organize and Auto Generate Code Specific for Connected Applications - this will allow for stateful context abstraction & less code within the Core Connector
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EmbeddedModelSchema,
    EmbeddedModelSchemaFromJSON,
    EmbeddedModelSchemaFromJSONTyped,
    EmbeddedModelSchemaToJSON,
    FlattenedAssets,
    FlattenedAssetsFromJSON,
    FlattenedAssetsFromJSONTyped,
    FlattenedAssetsToJSON,
    GroupedTimestamp,
    GroupedTimestampFromJSON,
    GroupedTimestampFromJSONTyped,
    GroupedTimestampToJSON,
    LocationTypeEnum,
    LocationTypeEnumFromJSON,
    LocationTypeEnumFromJSONTyped,
    LocationTypeEnumToJSON,
    PlatformEnum,
    PlatformEnumFromJSON,
    PlatformEnumFromJSONTyped,
    PlatformEnumToJSON,
} from './';

/**
 * 
 * @export
 * @interface FlattenedLocation
 */
export interface FlattenedLocation {
    /**
     * 
     * @type {EmbeddedModelSchema}
     * @memberof FlattenedLocation
     */
    schema?: EmbeddedModelSchema;
    /**
     * 
     * @type {string}
     * @memberof FlattenedLocation
     */
    id: string;
    /**
     * 
     * @type {LocationTypeEnum}
     * @memberof FlattenedLocation
     */
    type: LocationTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof FlattenedLocation
     */
    watch?: boolean;
    /**
     * This is the text of the path.
     * @type {string}
     * @memberof FlattenedLocation
     */
    text: string;
    /**
     * 
     * @type {GroupedTimestamp}
     * @memberof FlattenedLocation
     */
    created: GroupedTimestamp;
    /**
     * 
     * @type {GroupedTimestamp}
     * @memberof FlattenedLocation
     */
    updated: GroupedTimestamp;
    /**
     * 
     * @type {GroupedTimestamp}
     * @memberof FlattenedLocation
     */
    deleted?: GroupedTimestamp;
    /**
     * 
     * @type {FlattenedAssets}
     * @memberof FlattenedLocation
     */
    assets?: FlattenedAssets;
    /**
     * 
     * @type {PlatformEnum}
     * @memberof FlattenedLocation
     */
    platform?: PlatformEnum;
}

export function FlattenedLocationFromJSON(json: any): FlattenedLocation {
    return FlattenedLocationFromJSONTyped(json, false);
}

export function FlattenedLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlattenedLocation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'schema': !exists(json, 'schema') ? undefined : EmbeddedModelSchemaFromJSON(json['schema']),
        'id': json['id'],
        'type': LocationTypeEnumFromJSON(json['type']),
        'watch': !exists(json, 'watch') ? undefined : json['watch'],
        'text': json['text'],
        'created': GroupedTimestampFromJSON(json['created']),
        'updated': GroupedTimestampFromJSON(json['updated']),
        'deleted': !exists(json, 'deleted') ? undefined : GroupedTimestampFromJSON(json['deleted']),
        'assets': !exists(json, 'assets') ? undefined : FlattenedAssetsFromJSON(json['assets']),
        'platform': !exists(json, 'platform') ? undefined : PlatformEnumFromJSON(json['platform']),
    };
}

export function FlattenedLocationToJSON(value?: FlattenedLocation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'schema': EmbeddedModelSchemaToJSON(value.schema),
        'id': value.id,
        'type': LocationTypeEnumToJSON(value.type),
        'watch': value.watch,
        'text': value.text,
        'created': GroupedTimestampToJSON(value.created),
        'updated': GroupedTimestampToJSON(value.updated),
        'deleted': GroupedTimestampToJSON(value.deleted),
        'assets': FlattenedAssetsToJSON(value.assets),
        'platform': PlatformEnumToJSON(value.platform),
    };
}


