from _typeshed import Incomplete

class ModuleShim:
    def __init__(self, orig_module, handler) -> None: ...
    def __getattr__(self, name): ...
    def __setattr__(self, name, value) -> None: ...
    def __delattr__(self, name) -> None: ...
    def __dir__(self): ...

class DrakeDeprecationWarning(DeprecationWarning): ...

class _DeprecatedDescriptor:
    __doc__: Incomplete
    def __init__(self, original, message, *, date: Incomplete | None = ...) -> None: ...
    def __get__(self, obj, objtype): ...
    def __set__(self, obj, value) -> None: ...
    def __delete__(self, obj) -> None: ...

def deprecated(message, *, date: Incomplete | None = ...): ...
def install_numpy_warning_filters(force: bool = ...) -> None: ...
def deprecated_callable(message, *, date: Incomplete | None = ...): ...
