# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

from __future__ import annotations


class AirQualityModel:
    best_match = 0
    cams_global = 1
    cams_europe = 2
