# Version file autogenerated by the build process
version = '0.13.3'
build = 1259
vcs_info = 'Git SHA1 b078901d committed on 2023-10-12'
package_name = 'kintyre-splunk-conf'

SHELL_VER_VARS = 'KSCONF_VERSION="0.13.3"\nKSCONF_BUILD="1259"\nKSCONF_VCS_INFO="Git SHA1 b078901d committed on 2023-10-12"'

if __name__ == '__main__':
    print("# Please use 'python -m ksconf.version' instead.  This will eventually go away.")
    print(SHELL_VER_VARS)
