# coding: utf-8

"""
    Forgejo API.

    This documentation describes the Forgejo API.  # noqa: E501

    OpenAPI spec version: 1.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import forgejo_api
from forgejo_api.models.reference import Reference  # noqa: E501
from forgejo_api.rest import ApiException


class TestReference(unittest.TestCase):
    """Reference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReference(self):
        """Test Reference"""
        # FIXME: construct object with mandatory attributes with example values
        # model = forgejo_api.models.reference.Reference()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
