# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class PhysicianNetworkT(str, enum.Enum):
    """
    An enumeration.
    """

    WHEEL = "WHEEL"
    OPENLOOP = "OPENLOOP"

    def visit(self, wheel: typing.Callable[[], T_Result], openloop: typing.Callable[[], T_Result]) -> T_Result:
        if self is PhysicianNetworkT.WHEEL:
            return wheel()
        if self is PhysicianNetworkT.OPENLOOP:
            return openloop()
