from queue import Queue
q = Queue(maxsize=5)
print("Queue size before insertion: ",q.qsize())
print("Inserting elements......")
q.put('A')
q.put('AA')
q.put('AAA')
q.put('AAAA')
q.put('AAAAA')
print("After inserting elements: ",q.qsize())
print("Is queue full?",q.full())
print("Removing Elements.......")
print(q.get())
print(q.get())
print(q.get())
print(q.get())
print("Empty or not ?",q.empty())
print("Final size of queue: ",q.qsize())
