from _typeshed import Incomplete
from pydrake.systems.framework import LeafSystem as LeafSystem, PublishEvent as PublishEvent, TriggerType as TriggerType
from pydrake.systems.primitives import VectorLog as VectorLog
from pydrake.trajectories import Trajectory as Trajectory
from warnings import warn as warn

class PyPlotVisualizer(LeafSystem):
    time_step: Incomplete
    fig: Incomplete
    ax: Incomplete
    def __init__(self, draw_period: Incomplete | None = ..., facecolor=..., figsize: Incomplete | None = ..., ax: Incomplete | None = ..., show: Incomplete | None = ...) -> None: ...
    def draw(self, context) -> None: ...
    def start_recording(self) -> None: ...
    def stop_recording(self) -> None: ...
    def reset_recording(self) -> None: ...
    def get_recording_as_animation(self, **kwargs): ...
    def animate(self, log, resample: bool = ..., **kwargs): ...
