
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-16T09:41:42-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "2b10b9fd42913d6ef691ad64f0ad6499af948974",
 "version": "2.4.0rc4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
