
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-13T12:49:12-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "84e5c919c38b36456bf15704c9288fa6c1babdd0",
 "version": "0.2.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
