from ask_orex import Ox

WORD_CHAR = Ox("\\w")
ANY_CHAR = Ox(".")
DIGIT = Ox("\\d")
NON_DIGIT = Ox("\\D")
BOUNDARY = Ox("\\b")
SPACE = Ox("\\s")
TAB = Ox("\\t")
NEWLINE = Ox("\\n")
NON_WORD = Ox("\\W")
RETURN = Ox("\\r")
DOT = Ox("\\.")
BACKSLASH = Ox(r"\\")
ALPHA = Ox("[a-zA-Z]")
BLANK = Ox("[ \\t]")
PUNCTUATION = Ox("[!\"\\#$%&'()*+,\\-./:;<=>?@\\[\\]^_‘{|}~]")
UPPER_CHAR = Ox("[A-Z]")
LOWER_CHAR = Ox("[a-z]")
HEXDIGIT = Ox("[A-Fa-f0-9]")
ALNUM = Ox("\\w")
NON_ALNUM = Ox("\\W")
WORD = Ox("\\b(\\w+)\\b")
QUOTATION = Ox('"')
WHITESPACE = Ox("\\s")
NON_WHITESPACE = Ox("\\S")
BAR = Ox("\\|")
START = Ox("^")
END = Ox("$")
DASH = Ox("\\-")
