
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-16T13:43:02+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8ca8380ea88c7f69be17ebe67a05e823890964d1",
 "version": "5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
