from pydrake.common.containers import namedview as namedview
from pydrake.multibody.tree import JointActuatorIndex as JointActuatorIndex, JointIndex as JointIndex

def MakeNamedViewActuation(plant, view_name): ...
def MakeNamedViewPositions(plant, view_name, add_suffix_if_single_position: bool = ...): ...
def MakeNamedViewVelocities(plant, view_name, add_suffix_if_single_velocity: bool = ...): ...
def MakeNamedViewState(plant, view_name): ...
