import torch
from pathlib import Path
from typing import List, Optional, Tuple, Union

class PytorchLatencyEstimator:
    def __init__(self, model: torch.nn.Module, latency_type: str, **options) -> None: ...
    def record_item(self, n_base_samples: Union[float, int] = ...) -> None: ...
    def get_latencies(self, return_sample_time: bool = ...) -> Tuple[float, Optional[List[List[float]]]]: ...
    def export_chrome_trace(self, filename: Union[str, Path]) -> None: ...
