VERSION = '0.4.5'
CONFIG_FILE_MAC = '~/.snapser/config'
CONFIG_FILE_WIN = '%homepath%\.snapser\config'
DEFAULT_PROFILE = 'default'
API_KEY = 'SNAPSER_API_KEY'

SNAPCTL_SUCCESS = 0
SNAPCTL_ERROR = 1

# HTTP codes
HTTP_UNAUTHORIZED = 401
HTTP_FORBIDDEN = 403
HTTP_NOT_FOUND = 404
HTTP_CONFLICT = 409

# Error codes
ERROR_SERVICE_VERSION_EXISTS = 542
ERROR_TAG_NOT_AVAILABLE = 544
