from pathlib import Path
from typing import Union

def set_log_level(loglevel: int) -> None: ...
def enable_logging(enable: bool = ...) -> None: ...
def add_file_handler(path: Union[str, Path]) -> None: ...
