from enot.optimize import PretrainOptimizer, SearchOptimizer
from torch.optim import Optimizer
from typing import Union

OptimizerClass = Union[Optimizer, PretrainOptimizer, SearchOptimizer]

def log_begin(logger, optimizer: OptimizerClass) -> None: ...
def log_step(logger, optimizer: OptimizerClass, step: int) -> None: ...
def log_train_end(logger, optimizer: OptimizerClass, epoch: int) -> None: ...
def log_validation_end(logger, optimizer: OptimizerClass, epoch: int) -> None: ...
