import torch.nn as nn
from typing import Any, Dict, List

def build_mobilenet(search_ops: List[str], blocks_out_channels: List[int], blocks_count: List[int], blocks_stride: List[int], in_channels: int = ..., width_multiplier: float = ..., min_channels: int = ..., stem_params: Dict[str, Any] = ..., head_params: Dict[str, Any] = ..., init_weights_kn: bool = ..., dropout_rate: float = ..., num_classes: int = ...) -> nn.Sequential: ...
def build_frozen_mobilenet(blocks_op_name: List[str], blocks_out_channels: List[int], blocks_count: List[int], blocks_stride: List[int], in_channels: int = ..., width_multiplier: float = ..., min_channels: int = ..., stem_params: Dict[str, Any] = ..., head_params: Dict[str, Any] = ..., dropout_rate: float = ..., num_classes: int = ..., init_weights_kn: bool = ...) -> nn.Sequential: ...
