info = {"message": "chore: Bump label-studio-converter version to 0.0.57 (#4895)", "commit": "521e5ca88e1143ee132239574806224e852689f9", "date": "2023/10/13 14:49:37", "branch": "", "version": "1.9.1.post0+0.g521e5ca.dirty"}

# This file is automatically generated by version.py
# Do not include it to git!
