from _typeshed import Incomplete
from pydrake.common.jupyter import process_ipywidget_events as process_ipywidget_events
from pydrake.multibody.tree import JointIndex as JointIndex
from pydrake.systems.framework import BasicVector as BasicVector, PublishEvent as PublishEvent, VectorSystem as VectorSystem

class JointSliders(VectorSystem):
    def __init__(self, robot, lower_limit: float = ..., upper_limit: float = ..., resolution: float = ..., length: int = ..., update_period_sec: float = ...) -> None: ...
    def set_positions(self, q) -> None: ...
    def set_joint_positions(self, q) -> None: ...
    def DoCalcVectorOutput(self, context, unused, unused2, output) -> None: ...

def MakeJointSlidersThatPublishOnCallback(plant, publishing_system, root_context, my_callback: Incomplete | None = ..., lower_limit: float = ..., upper_limit: float = ..., resolution: float = ..., length: int = ..., continuous_update: bool = ...): ...
