

'''
	python3 STATUS.py "FOOD/USDA/FORM_1/STATUS/STATUS_1.py"
'''

import CYTE.FOOD.NIH.EXAMPLES as NIH_EXAMPLES
import CYTE.FOOD.NIH.FORM_1 as FORM_1

def CHECK_1 ():
	EXAMPLE = NIH_EXAMPLES.RETRIEVE ("TABLETS/MULTIVITAMIN_249664.JSON")
	RETURNS = FORM_1.MAKE (
		NIH_FOOD_DATA = EXAMPLE
	)
	
	#FORM_1 = RETURNS ["FORM"]
	NOTES = RETURNS ["NOTES"]
	

	assert (len (NOTES) == 0)

	return;
	
	
CHECKS = {
	"MULTIVITAMIN 2642759": CHECK_1
}