from enot.tensor_trace.tracing import Node as Node, OpNode as OpNode, ParameterNode as ParameterNode
from typing import List

def get_tracing_node_by_module_name(name: str, graph: List[Node]) -> OpNode: ...
def get_module_name_by_tracing_node(node: OpNode) -> str: ...
